version: '3.8'

services:
  db:
    image: postgres:13
    env_file: .env  
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    env_file: .env  
    environment:
      DATABASE_URL: ${URL_DATABASE}
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data: